/**
 * Check that every industry we mean to have a /tools page for actually has one.
 *
 * /tools now builds its grid from landing_pages alone, so its links resolve by
 * construction and cannot 404. What that change removed was the answer to a
 * different question: which industries are we *supposed* to cover? The keyword
 * list below used to live in the page and doubled as that checklist, so it
 * lives here now.
 *
 * The original bug is worth recording, because the shape recurs. The page had
 * two link sources — landing_pages rows, and this keyword list mapped to
 * /tools/pdf-to-excel-for-<slugified keyword> — with a filter meant to skip
 * keywords a row already covered. The filter compared a bare "accountants"
 * against slugs stored as "pdf-to-excel-for-accountants", never matched, and
 * dropped nothing. Result: 40 cards for 22 destinations, 18 of them exact
 * duplicate links, plus two 404s where slugification disagreed with the stored
 * slug ("e-commerce" vs "ecommerce", "hr-and-payroll" vs "hr-payroll").
 *
 * Nothing enforced that the two sources agreed, and the page looked fine.
 *
 * Usage: npx tsx scripts/audit-tools-links.ts
 * Exits non-zero when an intended industry has no page.
 */

import * as fs from "fs";
import * as path from "path";
import { createClient } from "@supabase/supabase-js";

const envPath = path.join(process.cwd(), ".env.local");
if (fs.existsSync(envPath)) {
  for (const line of fs.readFileSync(envPath, "utf-8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i === -1) continue;
    process.env[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? ""
);

/**
 * The industries /tools is meant to cover. Formerly SEO_KEYWORDS in
 * app/tools/page.tsx, where it was also a source of hrefs; it is only a
 * checklist now.
 */
const INTENDED_INDUSTRIES = [
  "Accountants", "Logistics", "Real Estate", "Healthcare", "E-commerce", "Law Firms",
  "Construction", "Insurance", "Bank Statements", "Invoices", "Purchase Orders",
  "Payday Stubs", "Freight Bills", "Medical Records", "Tax Returns", "Utility Bills",
  "Credit Card Statements", "Non-Profits", "Audit Teams", "HR & Payroll",
];

/**
 * Match an industry name to a landing_pages row.
 *
 * Deliberately loose. The stored slugs were generated by a transform that
 * disagreed with the page's own in two cases, so exact slug equality is what
 * produced the 404s in the first place. Comparing on letters and digits alone
 * makes "e-commerce" match "ecommerce" and "HR & Payroll" match "hr-payroll",
 * which is the answer a person would give.
 */
function letters(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function findRow(industry: string, slugs: string[]): string | null {
  const want = letters(industry);
  return (
    slugs.find((s) => letters(s) === `pdftoexcelfor${want}`) ??
    slugs.find((s) => letters(s).endsWith(want)) ??
    null
  );
}

async function run() {
  const { data, error } = await supabase.from("landing_pages").select("slug, industry");
  if (error) {
    console.error(`Could not read landing_pages: ${error.message}`);
    process.exit(1);
  }
  const rows = (data ?? []) as { slug: string; industry: string | null }[];
  const slugs = rows.map((r) => r.slug).filter((s) => s?.trim());

  console.log(`landing_pages rows: ${rows.length}`);
  console.log(`/tools renders one card per row, so it links to ${slugs.length} pages.\n`);

  const missing: string[] = [];
  for (const industry of INTENDED_INDUSTRIES) {
    const match = findRow(industry, slugs);
    if (match) console.log(`  ok       ${industry.padEnd(24)} -> /tools/${match}`);
    else {
      console.log(`  MISSING  ${industry.padEnd(24)} -> no landing_pages row`);
      missing.push(industry);
    }
  }

  // A row nobody asked for is not a problem, but it is worth seeing.
  const claimed = new Set(
    INTENDED_INDUSTRIES.map((i) => findRow(i, slugs)).filter((s): s is string => s !== null)
  );
  const extra = slugs.filter((s) => !claimed.has(s));
  if (extra.length) {
    console.log(`\n${extra.length} row(s) beyond the checklist (fine, just noting):`);
    for (const s of extra) console.log(`      /tools/${s}`);
  }

  // Duplicate slugs would mean duplicate cards. Impossible if the table has a
  // unique constraint, cheap to confirm if it does not.
  const dupes = slugs.filter((s, i) => slugs.indexOf(s) !== i);
  if (dupes.length) {
    console.log(`\nDUPLICATE landing_pages slugs — the grid renders these twice:`);
    for (const d of new Set(dupes)) console.log(`      ${d}`);
  }

  if (missing.length === 0 && dupes.length === 0) {
    console.log(`\nEvery intended industry has exactly one page.`);
    return;
  }
  if (missing.length) {
    console.log(
      `\n${missing.length} industry/industries have no page. /tools no longer links to\n` +
        `pages that do not exist, so this is missing coverage rather than a broken\n` +
        `link — add a landing_pages row for each to bring it back.`
    );
  }
  // Set the code rather than exiting, so Supabase's socket closes cleanly.
  process.exitCode = 1;
}

run();
